import type { ImmersiveStation } from "@/components/immersive/scene/types";

export const immersiveStations: ImmersiveStation[] = [
  {
    id: "rules",
    content: "rules",
    label: "Regeltisch",
    detail: "Stimmzettel holen und Regelwerk lesen",
    x: 730,
    y: 315,
    width: 112,
    height: 125,
  },
  {
    id: "booth-1",
    content: "wahl",
    label: "Wahlkabine 1",
    detail: "Wahlrahmen, Module und Prioritäten bearbeiten",
    x: 190,
    y: 112,
    width: 102,
    height: 132,
  },
  {
    id: "booth-2",
    content: "wahl",
    label: "Wahlkabine 2",
    detail: "Wahlrahmen, Module und Prioritäten bearbeiten",
    x: 330,
    y: 112,
    width: 103,
    height: 132,
  },
  {
    id: "booth-3",
    content: "wahl",
    label: "Wahlkabine 3",
    detail: "Wahlrahmen, Module und Prioritäten bearbeiten",
    x: 474,
    y: 112,
    width: 102,
    height: 132,
  },
  {
    id: "booth-4",
    content: "timetable",
    label: "Stundenplan",
    detail: "Modulstundenplan ansehen",
    x: 615,
    y: 112,
    width: 100,
    height: 132,
  },
  {
    id: "review",
    content: "review",
    label: "Prüftisch & Wahlurne",
    detail: "Zusammenfassung prüfen und Stimmzettel abgeben",
    x: 137,
    y: 330,
    width: 140,
    height: 120,
  },
];
